ALTER TABLE guild_file
ADD time_added timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE files
ADD time_added timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
ADD time_added timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE guild
ADD time_added timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
